---
- name: Update package index
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install Ubuntu packages
  ansible.builtin.apt:
    name: "{{ postinstall_extra_packages_ubuntu }}"
    state: present
