services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENABLE_IPV6: false
      PER_VHOST: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
    networks:
      - cicd_network

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/acme:/etc/acme.sh
    networks:
      - cicd_network

  jenkins:
    image: thfx31/ynov:jenkins-v1
    container_name: jenkins_server
    restart: always
    environment:
      VIRTUAL_HOST: ${JENKINS_DOMAIN}
      LETSENCRYPT_HOST: ${JENKINS_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 8080
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd_network

  gitlab:
    image: thfx31/ynov:gitlab-v1
    container_name: gitlab_server
    hostname: ${GITLAB_DOMAIN}
    restart: always
    environment:
      VIRTUAL_HOST: ${GITLAB_DOMAIN}
      LETSENCRYPT_HOST: ${GITLAB_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_DOMAIN}';
        nginx['enable'] = false
        gitlab_rails['gitlab_https'] = true
        gitlab_rails['trusted_proxies'] = ['172.24.0.0/16']
        unicorn['port'] = 8080
    shm_size: '256m'
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    networks:
      - cicd_network

networks:
  cicd_network:
    driver: bridge
