services:
  openssl:
    build: .
    container_name: openssl-cert-generator
    volumes:
      - ./certs:/certs
    environment:
      CERT_CN: mydomain.com
      CERT_DAYS: 365
      CERT_KEY_FILE: mydomain.key
      CERT_CRT_FILE: mydomain.crt

