---
- name: Check if Trivy is already installed
  ansible.builtin.command: which trivy
  register: trivy_check
  changed_when: false
  failed_when: false

- name: Install prerequisites for Trivy
  ansible.builtin.apt:
    name: "{{ trivy_requirements_packages }}"
    state: present
    update_cache: true
  when: trivy_check.rc != 0

- name: Add GPG key
  ansible.builtin.apt_key:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    state: present

- name: Add Trivy repository
  ansible.builtin.apt_repository:
    repo: deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main
    state: present
    filename: trivy

- name: Install Trivy
  ansible.builtin.apt:
    name: trivy
    state: present
    update_cache: true

- name: Create reports directory
  ansible.builtin.file:
    path: "{{ trivy_forge_cicd_docker_path }}/reports"
    state: directory
    mode: "0755"

- name: List Docker images
  ansible.builtin.command:
    cmd: docker compose images --format json
    chdir: "{{ trivy_forge_cicd_docker_path }}"
  register: trivy_docker_images
  changed_when: false

- name: Scan Docker images with Trivy
  ansible.builtin.command: >
    trivy image --quiet --format template
    --template "@/usr/local/share/trivy/templates/html.tpl"
    --output {{ trivy_forge_cicd_docker_path }}/reports/{{ item.Repository | replace('/', '_') }}_{{ item.Tag }}.html
    {{ item.Repository }}:{{ item.Tag }}
  loop: "{{ trivy_docker_images.stdout | from_json }}"
  changed_when: false
  failed_when: trivy_scan.rc not in [0, 1]

- name: Find Trivy reports
  ansible.builtin.find:
    paths: "{{ trivy_forge_cicd_docker_path }}/reports"
    patterns: "*.html"
    recurse: false
  register: trivy_reports_to_fetch

- name: Print Trivy reports to fetch
  ansible.builtin.debug:
    msg: "Fetch files : {{ trivy_reports_to_fetch.files | map(attribute='path') }}"

- name: Fetch Trivy reports
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: ../reports/
    flat: true
  loop: "{{ trivy_reports_to_fetch.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
