---
- name: Create docker directory
  ansible.builtin.file:
    path: "{{ forge_cicd_docker_path }}"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy Docker Compose
  ansible.builtin.copy:
    src: ../docker-compose.yml
    dest: "{{ forge_cicd_docker_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  register: forge_cicd_compose_copy

- name: Copy environment file
  ansible.builtin.copy:
    src: .env
    dest: "{{ forge_cicd_docker_path }}/.env"
    mode: "600"
  register: forge_cicd_env_copy

# Only if prompted for Docker Hub credentials and need custom images
- name: Connect to Docker Hub
  community.docker.docker_login:
    username: "{{ docker_hub_user }}"
    password: "{{ docker_hub_token }}"

- name: Pull and ensure containers are running
  community.docker.docker_compose_v2:
    project_src: "{{ forge_cicd_docker_path }}"
    state: present
    pull: always
    recreate: always
  when: forge_cicd_compose_copy.changed or forge_cicd_env_copy.changed

- name: Check containers status
  ansible.builtin.command: docker ps --format '{% raw %}{{.Names}}{% endraw %}'
  register: forge_cicd_running_containers
  changed_when: false

- name: Print running containers
  ansible.builtin.debug:
    msg: "{{ item }} is running"
  loop: "{{ forge_cicd_running_containers.stdout_lines }}"
  when: forge_cicd_running_containers.stdout_lines is defined and forge_cicd_running_containers.stdout_lines | length > 0

- name: Status summary
  ansible.builtin.debug:
    msg: >-
      {% if forge_cicd_compose_copy.changed or forge_cicd_env_copy.changed %}
      Configuration files modified. Docker Compose has been redeployed.
      {% else %}
      No changes detected on 'docker-compose.yml' or '.env'. Deployment unchanged.
      {% endif %}
