---
- name: Remove Podman and old Docker
  ansible.builtin.dnf:
    name: "{{ docker_remove_packages}}"
    state: absent

- name: Install Dnf Plugins
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository
  ansible.builtin.shell: |
      dnf config-manager --add-repo {{ docker_rhel_repo }}

- name: Update repository
  ansible.builtin.dnf:
    update_cache: yes

- name: Install docker
  ansible.builtin.dnf:
    name: "{{ docker_install_packages}}"
    state: present

- name: Start and enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_group }}"
    append: yes