---
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        args: [--force-color, ansible/]
        files: ^ansible/
